connection:
  type: "snowflake"
  account: "XUUJXTV-EE80968"
  user: "MAHESH"
  role: "ACCOUNTADMIN"
  warehouse: "COMPUTE_WH"
  database: "CICD"
  schema: "DRAI_CICD"
  session_parameters:
    TIMEZONE: "UTC"
    AUTOCOMMIT: true
  authentication:
    method: "password"                     # changed from keypair
    password: "${SNOWFLAKE_PASSWORD}"   #$env:SNOWFLAKE_PASSWORD = "YourStrongPassword"
    private_key_path: "C:\\Users\\krish\\.ssh\\rsa_key.p8"
    private_key_passphrase: "${SNOWFLAKE_KEY_PASSPHRASE}"   # uses env var, never 